modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rbmkreactor"
version="${file.jarVersion}"
displayName="RBMK Reactor"
authors="CoolkidGUI"
description='''
An advanced RBMK-inspired reactor simulation mod with control profiles,
multistage failures, persistent fallout, and high-intensity disaster chains.
'''

[[dependencies.rbmkreactor]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rbmkreactor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
